name: traffic-ml
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.9
  - pip
  - pip:
      - torch==2.1.2+cpu
      - torchvision==0.16.2+cpu
      - torchaudio==2.1.2+cpu
      - --extra-index-url https://download.pytorch.org/whl/cpu
      - ultralytics==8.1.0
      - opencv-python==4.9.0.80
      - numpy==1.26.4
      - pandas==2.2.2
      - scikit-learn==1.3.2
      - matplotlib==3.8.2
      - flask==3.0.2
      - Werkzeug==3.0.1
      - joblib==1.3.2
      - tqdm==4.66.2
