name: traffic-venv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - ultralytics==8.1.0
    - opencv-python==4.9.0.80
    - numpy==1.26.4
    - pandas==2.2.2
    - scikit-learn==1.4.1
    - matplotlib==3.8.2
    - flask==3.0.2
    - joblib==1.3.2
